### ISSUE TITLE
Required fields not indicated in default template order form

### ISSUE THREAD

**Issue by jaywink** [shoopio/shoop#207]
For billing form for example as shown below:

![selection_164](https://cloud.githubusercontent.com/assets/1174866/10268847/0055e2f2-6ace-11e5-8ab0-06cadff5213a.png)
![selection_165](https://cloud.githubusercontent.com/assets/1174866/10268849/02b8601a-6ace-11e5-8f24-bef6eb88e80a.png)

**Comment by juhakujala** [comment]
We are planning on removing the "default template" since we have been working with the new "classic gray theme". Default template has no additional styles by us, it only has what bootstrap has to offer :)

**Comment by jaywink** [comment]
I saw default template was removed. Do issues belong still here since I understand it will be in the marketplace, or should I file this in the new repo it has/will have?

> Default template has no additional styles by us, it only has what bootstrap has to offer :)

Not indicating required fields is still a bug in the theme ;) I fixed my local project with:

    div#billing div.required-field label.control-label::after,
    div#shipping div.required-field label.control-label::after {
        content: " *";
    }

Can push a PR to the new theme repo if wanted.

**Comment by juhakujala** [comment]
The new theme can be found here: https://github.com/shoopio/shoop-simple-theme

**Comment by jaywink** [comment]
Moved to correct repo.
