### ISSUE TITLE
Mithril.js 0.2.1 breaks admin UI

### ISSUE THREAD

**Issue by jaywink** [shoopio/shoop#298]
Editing views break with mithril.js 0.2.1 (with `"mithriljs": "~0.2.0",`). These are possibly fixed by 0.2.2-rc.1, according to changelog, but the way Shoop locks dependencies doesn't pull that in.

Locked my fork dep to 0.2.0 and admin edit views work again.

Question: why are Python dependencies locked to patch level but JavaScript not? Not locking dependencies causes each new environment to get a different version of the libraries, which can cause havoc with package maintainers breaking things at patch level. Could Shoop also lock javascript dependencies to patch level for increased stability?

http://nvie.com/posts/pin-your-packages/

**Comment by akx** [comment]
The JavaScript ecosystem is (predominantly -- well, practically fully) Semver based, so the `"mithriljs": "~0.2.0"` dependency spec we have should only pull in versions that are compatible (as the 0.0.x level is patches only).

The Mithril 0.2.1 release was a human mishap in that sense, as it had, as I understand, multiple regressions which caused the trouble you're (or were) facing.

However, you're right in that we _should_ lock down JS packages whose version is < 1.0, as the Semver spec also specifies that within the 0.x.x series, any changes are allowed.

**Comment by suutari-ai** [comment]
How does the admin UI break with Mithril 0.2.1?

**Comment by suutari-ai** [comment]
Created an issue to Shoop backlog for this: SHOOP-2029

**Comment by jaywink** [comment]
Sorry, could have specified or taken a screenshot, but I had already rolled back at this point. Basically for example creating a new product, the whole sidebar fails to exist. Select widgets etc don't work. In the console there were some errors about undefined stuff. Sorry I have no more exact errors, best to try it.

**Comment by suutari-ai** [comment]
@jaywink Thanks. We also found out that product selector, image selector etc. don't work.

**Comment by akx** [comment]
This is fixed by #307, so closing. Thanks again!
