### ISSUE TITLE
Statics not built/collected for admin

### ISSUE THREAD

**Issue by jaywink** [shoopio/shoop#33]
Added Shoop current master to requirements (from git), installed and it did lots of nice build jobs as such. In my project I then did `collectstatic`, loaded up the shop and front page looks good. However, going to `/sa` shows admin statics were not collected. Verified in my static folder they are missing. Also they are not in `/static/shoop_admin` in the site packages, only images and fonts there. So more likely a build issue than collection issue.

![selection_091](https://cloud.githubusercontent.com/assets/1174866/8451496/6567469a-1fec-11e5-9029-b19e29190e8d.png)

The build job did build them, the pip install ended with:

```
    *** (1/2) Building: ./shoop/notify
    Saving build result of ./shoop/notify
    Caching to: /home/jaywink/.cache/shoop/build_resources/prod/00/ea603f7ecf1406b9067f9318ae8118411eb0b9/static/notify/admin/script-editor-bundle.js
    *** (2/2) Building: ./shoop/admin
    Saving build result of ./shoop/admin
    Caching to: /home/jaywink/.cache/shoop/build_resources/prod/e4/3133f611bedb3b59e4abeb4678afd3c9128021/static/shoop_admin/js/picotable.js
    Caching to: /home/jaywink/.cache/shoop/build_resources/prod/e4/3133f611bedb3b59e4abeb4678afd3c9128021/static/shoop_admin/js/base.js
    Caching to: /home/jaywink/.cache/shoop/build_resources/prod/e4/3133f611bedb3b59e4abeb4678afd3c9128021/static/shoop_admin/js/dashboard.js
    Caching to: /home/jaywink/.cache/shoop/build_resources/prod/e4/3133f611bedb3b59e4abeb4678afd3c9128021/static/shoop_admin/js/media-browser.js
    Caching to: /home/jaywink/.cache/shoop/build_resources/prod/e4/3133f611bedb3b59e4abeb4678afd3c9128021/static/shoop_admin/js/vendor.js
    Caching to: /home/jaywink/.cache/shoop/build_resources/prod/e4/3133f611bedb3b59e4abeb4678afd3c9128021/static/shoop_admin/js/remarkable.js
    Caching to: /home/jaywink/.cache/shoop/build_resources/prod/e4/3133f611bedb3b59e4abeb4678afd3c9128021/static/shoop_admin/css/media-browser.css
    Caching to: /home/jaywink/.cache/shoop/build_resources/prod/e4/3133f611bedb3b59e4abeb4678afd3c9128021/static/shoop_admin/css/base.css
    Caching to: /home/jaywink/.cache/shoop/build_resources/prod/e4/3133f611bedb3b59e4abeb4678afd3c9128021/static/shoop_admin/css/dashboard.css
Successfully installed shoop
Cleaning up...
```

Something missing that pushes them to the static folder for collection?

shoop==1.0.0.post0.dev78-g8bb9e05
pip 1.5.6
Python 3.4.3
Ubuntu 15.04

Oh and btw, not sure if intended, but if I install from git with pip using the `-e` flag, the builds are not triggered at all.

**Comment by akx** [comment]
This should be resolved in PR #32 (commit f258cb53e5fb797190bb22bdf6a1669a7e41506a).

**Comment by akx** [comment]
Can you try this again with the current master (since #32 is now merged)? :)

**Comment by jaywink** [comment]
Thanks, works like a charm! :cookie: 

Btw, while it was running this time there was no output, which looks clean but on my i3 laptop it took at least a minute which might be confusing for someone. But I guess cleaner output is better, just saying if that was not intended.

![selection_083](https://cloud.githubusercontent.com/assets/1174866/8476025/c50c3388-20c5-11e5-820b-d4c38803883e.png)

**Comment by suutari-ai** [comment]
Can't do much about that, since it's pip that is hiding the output of the build process. If you do `python setup.py instal` directly (in venv to not pollute your global env) instead of through pip, you should get the output of the build step. Anyway, this should be no issue when we have published the Wheel, since it will contain the built resources and therefore installs instantaneously, and pip will use a wheel is one is available.
