### ISSUE TITLE
Pages availability is confusing and missing date pickers

### ISSUE THREAD

**Issue by jaywink** [shoopio/shoop#34]
I created a page and set it `Visible in menu`. The "from" and "to" fields don't have date pickers and I thought they would be optional anyway, seems logical to me as saving works without filling them.

My page didn't appear in shop side. I then went back and manually typed a date "2014-01-01", saved, and pages menu appeared.

So, imho `from` and `to` should be optional constraints and they should definitely have date pickers.

![selection_085](https://cloud.githubusercontent.com/assets/1174866/8476154/269eb5c0-20c7-11e5-87ed-c564c8cd0194.png)

**Comment by akx** [comment]
Leaving the availability fields both empty means "this page is not published at all", which, I guess, should be documented :)

And as for date pickers, [if we only had viable native support...](http://caniuse.com/#feat=input-datetime)

**Comment by jaywink** [comment]
> Leaving the availability fields both empty means "this page is not published at all", which, I guess, should be documented :)

Well, the UX is confusing, I don't think documentation helps there. What is the reason for even having "visible in menu" if it doesn't do anything without also filling "available from"? Maybe just remove the checkbox and just use the date, if that is required anyway?

If the checkbox just means "visible in menu" as it says, but "available from" controls whether the page works - then there is probably a bug since I could access the page even without setting any dates by guessing the url :)

**Comment by jaywink** [comment]
Any plans on datepickers? ;) Feels like quite an important usability thing.

Also, hint on valid format might be good in error message as there is no date pickers yet:
![selection_159](https://cloud.githubusercontent.com/assets/1174866/10265202/f53ccb78-6a2e-11e5-843f-ff50502062d0.png)

**Comment by akx** [comment]
Date pickers are being tracked as SHOOP-1612, being put into place by @juhakujala as we speak.
