### ISSUE TITLE
Xtheme plugin API requires private import

### ISSUE THREAD

**Issue by akx** [shoopio/shoop#360]
The commit https://github.com/shoopio/shoop/commit/71b6269b5de89f7a89b91fea55d6eadd9a026868 made it so that external consumers of the Xtheme plugin API (such as themes and addons) must use a private import (`from xtheme.plugins._base import TemplatedPlugin`).

This isn't very clean imho.

Assigning @suutari-ai as the original author of the mentioned API cleanup commit.

**Comment by suutari-ai** [comment]
No, you shouldn't use any private imports. TemplatedPlugin is available as shoop.xtheme.TemplatedPlugin. That's what you should be using. See the docs:
http://shoop.readthedocs.org/en/v3.0.0/api/shoop.xtheme.html#shoop.xtheme.TemplatedPlugin

**Comment by akx** [comment]
Ah, I see. Didn't notice the changes to `xtheme/__init__.py`.

**Comment by suutari-ai** [comment]
No problem. Good that you pointed this out.

Btw. the change is also mentioned in the release notes:
http://shoop.readthedocs.org/en/latest/release_notes/3.0.0.html#updating-from-2-0
