### ISSUE TITLE
New User Register Error 

### ISSUE THREAD

**Issue by tanvirraj** [shoopio/shoop#411]
when i trying to to register as a new user i am getting error 

![screen shot 2016-04-13 at 2 42 05 pm](https://cloud.githubusercontent.com/assets/3768120/14487599/49d9add4-0185-11e6-945e-aa884ab1b281.png)

**Comment by suutari-ai** [comment]
Can you post the full traceback too? (Click the "Switch to copy-and-paste view" link in that page and copy-paste that text here as comment.)

Also, which version of django-registration-redux you are using? Some other Python package version might be also relevant, so can you post the output of `pip freeze` too?

**Comment by tanvirraj** [comment]
@suutari-ai  hello thanks for you help 
here is copy-and-paste view 
`Environment:


Request Method: POST
Request URL: http://localhost:8000/register/

Django Version: 1.8.12
Python Version: 2.7.9
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.messages',
 'django.contrib.sessions',
 'django.contrib.staticfiles',
 'shoop.themes.classic_gray',
 'shoop.addons',
 'shoop.admin',
 'shoop.api',
 'shoop.core',
 'shoop.default_tax',
 'shoop.front',
 'shoop.front.apps.auth',
 'shoop.front.apps.customer_information',
 'shoop.front.apps.personal_order_history',
 'shoop.front.apps.registration',
 'shoop.front.apps.simple_order_notification',
 'shoop.front.apps.simple_search',
 'shoop.notify',
 'shoop.simple_cms',
 'shoop.simple_pricing',
 'shoop.simple_supplier',
 'shoop.order_printouts',
 'shoop.testing',
 'shoop.utils',
 'shoop.xtheme',
 'bootstrap3',
 'django_jinja',
 'easy_thumbnails',
 'filer',
 'registration',
 'rest_framework',
 'shoop.discount_pricing']
Installed Middleware:
['django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'shoop.front.middleware.ProblemMiddleware',
 'shoop.front.middleware.ShoopFrontMiddleware']


Traceback:
File "/Users/tanvir/.virtualenvs/shoop/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  132.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/Users/tanvir/.virtualenvs/shoop/lib/python2.7/site-packages/django/views/generic/base.py" in view
  71.             return self.dispatch(request, *args, **kwargs)
File "/Users/tanvir/code/django/shoop/shoop/front/apps/registration/views.py" in dispatch
  54.         return view_class.as_view()(request, *args, **kwargs)
File "/Users/tanvir/.virtualenvs/shoop/lib/python2.7/site-packages/django/views/generic/base.py" in view
  71.             return self.dispatch(request, *args, **kwargs)
File "/Users/tanvir/.virtualenvs/shoop/lib/python2.7/site-packages/django/utils/decorators.py" in _wrapper
  34.             return bound_func(*args, **kwargs)
File "/Users/tanvir/.virtualenvs/shoop/lib/python2.7/site-packages/django/views/decorators/debug.py" in sensitive_post_parameters_wrapper
  76.             return view(request, *args, **kwargs)
File "/Users/tanvir/.virtualenvs/shoop/lib/python2.7/site-packages/django/utils/decorators.py" in bound_func
  30.                 return func.__get__(self, type(self))(*args2, **kwargs2)
File "/Users/tanvir/.virtualenvs/shoop/lib/python2.7/site-packages/registration/views.py" in dispatch
  39.         return super(RegistrationView, self).dispatch(request, *args, **kwargs)
File "/Users/tanvir/.virtualenvs/shoop/lib/python2.7/site-packages/django/views/generic/base.py" in dispatch
  89.         return handler(request, *args, **kwargs)
File "/Users/tanvir/.virtualenvs/shoop/lib/python2.7/site-packages/django/views/generic/edit.py" in post
  215.             return self.form_valid(form)
File "/Users/tanvir/.virtualenvs/shoop/lib/python2.7/site-packages/registration/views.py" in form_valid
  43.         success_url = self.get_success_url(new_user)

Exception Type: TypeError at /register/
Exception Value: get_success_url() takes exactly 3 arguments (2 given)
`
and here is my `pip freeze` result 

`alabaster==0.7.7
Babel==2.3.2
Django==1.8.12
django-bootstrap3==6.2.2
django-countries==3.4.1
django-enumfields==0.7.4
django-filer==1.1.1
django-jinja==1.4.2
django-mptt==0.8.3
django-parler==1.6.2
django-parler-rest==1.3
django-polymorphic==0.8.1
django-registration-redux==1.4
django-timezone-field==1.3
djangorestframework==3.2.5
docutils==0.12
easy-thumbnails==2.3
enum34==1.0.4
factory-boy==2.6.1
fake-factory==0.5.7
imagesize==0.7.0
ipaddress==1.0.16
Jinja2==2.8
jsonfield==1.0.3
Markdown==2.6.6
MarkupSafe==0.23
Pillow==3.2.0
Pygments==2.1.3
python-dateutil==2.5.2
pytoml==0.1.7
pytz==2016.3
requests==2.9.1
-e git+git@github.com:tanvirraj/shoop.git@783c1ea1ceb27db0090853f485d8bcf436f5f9c4#egg=shoop
six==1.10.0
snowballstemmer==1.2.1
Sphinx==1.4
Unidecode==0.4.19
vboxapi==1.0
wheel==0.26.0`

**Comment by tanvirraj** [comment]
@suutari-ai  i guess this a form validation problem as stackoverflow , 
http://stackoverflow.com/questions/20905510/django-registration-form-valid-takes-exactly-2-arguments-3-given

can you give me a idea how can i edit 
this line 
`Exception Location:/Users/tanvir/.virtualenvs/shoop/lib/python2.7/site-packages/registration/views.py in form_valid, line 43`

i mean django registration package

**Comment by tulimaki** [comment]
Your ``django-registration-redux`` is in wrong version. Since we have made some customization to registration process the newest version is not currently supported. I would suggest you to install version 1.3.

**Comment by suutari-ai** [comment]
Should be fixed in commit 4375ded043ace2949ce6cc20f2bffbd6bdfd2957, which adds support for django-registration-redux 1.4.
