### ISSUE TITLE
Deactivate language

### ISSUE THREAD

**Issue by ijharulislam** [shoopio/shoop#515]
How to deactivate languages like chinese and others. I want to use only English.

**Comment by suutari-ai** [comment]
You can do this in your Django project's settings file. Just set the LANGUAGES setting to just English:
```python
from django.utils.translation import ugettext_lazy as _

LANGUAGES = (
    ('en', _('English')),
)
```
See https://docs.djangoproject.com/en/1.8/ref/settings/#languages for details.

**Comment by landaverdelbo** [comment]
Hi , i want to use only Spanish Mexico

LANGUAGES = [
      ('es-MX', 'Espanol Mexico'),
]
 but i got this error

this for pages:
(1062, "Duplicate entry 'contacto' for key 'url'")

**Comment by landaverdelbo** [comment]
i can see in tables database that any row is saved twice, one in "en" and another in "es-MX", 
but when a only set one language- the app tray to save the same row twice-- both on "es-MX", this trigger the error.
(1062, "Duplicate entry 'contacto' for key 'url'")
